# id -> (full phrase as it appears in the stem, its tone-marked pinyin)
# Applied by merge_banks.py so that every Chinese run in a question stem has a
# pinyin reading shown beside it in the practice area.
STEM_PY = {
 "B056": ("好吃嗎？", "hǎochī ma?"),
 "B061": ("今天星期幾？", "jīntiān xīngqí jǐ?"),
 "B069": ("生病了", "shēngbìng le"),
 "B071": ("你叫什麼名字？", "nǐ jiào shénme míngzi?"),
 "B072": ("你幾歲？", "nǐ jǐ suì?"),
 "B073": ("你是哪一國人？", "nǐ shì nǎ yì guó rén?"),
 "B082": ("明天見", "míngtiān jiàn"),
 "B094": ("關電燈", "guān diàndēng"),
 "B102": ("中文怎麼說？", "zhōngwén zěnme shuō?"),
 "B107": ("錯了", "cuò le"),
 "B110": ("我很忙", "wǒ hěn máng"),
 "B111": ("好累", "hǎo lèi"),
 "B118": ("體育課", "tǐyù kè"),
 "B121": ("三年級", "sān niánjí"),
 "B123": ("起立、敬禮", "qǐlì, jìnglǐ"),
 "B149": ("我們來拍照", "wǒmen lái pāizhào"),
 "B154": ("廁所在右邊", "cèsuǒ zài yòubiān"),
 "B158": ("我沒帶課本", "wǒ méi dài kèběn"),
 "B159": ("我可以借嗎？", "wǒ kěyǐ jiè ma?"),
 "B162": ("念一次", "niàn yí cì"),
 "B163": ("寫下來", "xiě xiàlái"),
 "B166": ("你喜歡台灣嗎？", "nǐ xǐhuān Táiwān ma?"),
 "B167": ("你會說中文嗎？", "nǐ huì shuō zhōngwén ma?"),
 "B169": ("好熱", "hǎo rè"),
 "B170": ("今天很冷", "jīntiān hěn lěng"),
 "B178": ("操場集合", "cāochǎng jíhé"),
 "I034": ("教務主任", "jiàowù zhǔrèn"),
 "I055": ("一張紙", "yì zhāng zhǐ"),
 "I056": ("書", "shū"),
 "I057": ("一台電腦", "yì tái diànnǎo"),
 "I058": ("一間教室", "yì jiān jiàoshì"),
 "I078": ("視力檢查", "shìlì jiǎnchá"),
 "I082": ("建立常規", "jiànlì chángguī"),
 "I089": ("跟家長溝通", "gēn jiāzhǎng gōutōng"),
 "I135": ("共同備課", "gòngtóng bèikè"),
 "I150": ("國際交流", "guójì jiāoliú"),
 "I152": ("視訊交流", "shìxùn jiāoliú"),
 "I158": ("待核章", "dài hézhāng"),
 "I161": ("一件事", "yí jiàn shì"),
 "I162": ("三份資料", "sān fèn zīliào"),
 "I163": ("請給我資料", "qǐng gěi wǒ zīliào"),
 "I166": ("報名截止", "bàomíng jiézhǐ"),
 "I167": ("活動延期", "huódòng yánqí"),
 "I177": ("確定了嗎？", "quèdìng le ma?"),
 "I179": ("請配合", "qǐng pèihé"),
 "A031": ("已核定", "yǐ hédìng"),
 "A033": ("公文的主旨", "gōngwén de zhǔzhǐ"),
 "A034": ("公文的說明", "gōngwén de shuōmíng"),
 "A043": ("計畫執行", "jìhuà zhíxíng"),
 "A044": ("檢討會議", "jiǎntǎo huìyì"),
 "A064": ("貴賓蒞臨", "guìbīn lìlín"),
 "A066": ("校長致詞", "xiàozhǎng zhìcí"),
 "A085": ("教材研發", "jiàocái yánfā"),
 "A087": ("課綱的學習表現", "kègāng de xuéxí biǎoxiàn"),
 "A090": ("十年樹木，百年樹人", "shí nián shù mù, bǎi nián shù rén"),
 "A104": ("依規定辦理", "yī guīdìng bànlǐ"),
 "A118": ("專題研究", "zhuāntí yánjiù"),
 "A121": ("朗讀比賽", "lǎngdú bǐsài"),
 "A131": ("偏鄉學校", "piānxiāng xuéxiào"),
 "A132": ("弱勢學生", "ruòshì xuéshēng"),
 "A140": ("補助辦法", "bǔzhù bànfǎ"),
 "A153": ("線上教學", "xiànshàng jiàoxué"),
 "A154": ("實體課程", "shítǐ kèchéng"),
 "A157": ("檢核表", "jiǎnhébiǎo"),
 "A162": ("達成共識", "dáchéng gòngshì"),
 "A163": ("請提出具體建議", "qǐng tíchū jùtǐ jiànyì"),
 "A166": ("落實政策", "luòshí zhèngcè"),
 "A167": ("永續發展", "yǒngxù fāzhǎn"),
 "A179": ("揭牌儀式", "jiēpái yíshì"),
 "A180": ("締結姊妹校", "dìjié jiěmèi xiào"),
}
