#!/usr/bin/env python3
"""Regenerate .pages-exclude — the list of image files that no page references.

These files stay in the repo but are excluded from the PUBLISHED GitHub Pages
artifact, keeping the deployed site under Pages' 1GB hard limit.

Run from the repo root:  python3 tools/gen-pages-exclude.py

Matching is by basename: an image is kept if its filename appears anywhere in
any text file. This errs toward KEEPING files (a false match keeps a file we
could have dropped) — it never drops a referenced image. Re-run whenever you
add photos or wire up new pages.
"""
import os, re
from urllib.parse import unquote

IMG_EXT = (".jpg", ".jpeg", ".png", ".gif", ".webp")  # .svg always kept (tiny)
TEXT_EXT = (".html", ".htm", ".css", ".js", ".json", ".md", ".xml", ".txt", ".yml", ".yaml")
SKIP = (".git", ".github")

refs = set()
tref = re.compile(r'[^\s"\'()<>]+\.(?:jpg|jpeg|png|gif|webp|svg)', re.I)
for dp, dns, fns in os.walk("."):
    dns[:] = [d for d in dns if d not in SKIP]
    for fn in fns:
        if not fn.lower().endswith(TEXT_EXT):
            continue
        try:
            txt = open(os.path.join(dp, fn), encoding="utf-8").read()
        except Exception:
            continue
        for m in tref.findall(txt):
            refs.add(os.path.basename(unquote(m)).lower())

unref = []
total = 0
for dp, dns, fns in os.walk("."):
    dns[:] = [d for d in dns if d not in SKIP]
    for fn in fns:
        if not fn.lower().endswith(IMG_EXT):
            continue
        if fn.lower() not in refs:
            unref.append(os.path.join(dp, fn)[1:])  # strip '.', keep leading '/'
            total += os.path.getsize(os.path.join(dp, fn))

unref.sort()
with open(".pages-exclude", "w", encoding="utf-8") as f:
    f.write("# Auto-generated by tools/gen-pages-exclude.py\n")
    f.write("# Images not referenced by any page. Excluded from the PUBLISHED Pages\n")
    f.write("# artifact only; files remain in the repo. Re-run the script after\n")
    f.write("# adding photos or wiring up new pages.\n")
    for p in unref:
        f.write(p + "\n")
print(f"wrote .pages-exclude: {len(unref)} files, {total/1048576:.0f} MB excluded from publish")
