#!/usr/bin/env python3
"""Regenerate .pages-exclude — the list of image files that no page references.

These files stay in the repo but are excluded from the PUBLISHED GitHub Pages
artifact, keeping the deployed site under Pages' 1GB hard limit.

Run from the repo root:  python3 tools/gen-pages-exclude.py

Matching is by basename: an image is kept if its filename appears anywhere in
any text file. This errs toward KEEPING files (a false match keeps a file we
could have dropped) — it never drops a referenced image. Re-run whenever you
add photos or wire up new pages.
"""
import os, re
from urllib.parse import unquote

IMG_EXT = (".jpg", ".jpeg", ".png", ".gif", ".webp")  # .svg always kept (tiny)
TEXT_EXT = (".html", ".htm", ".css", ".js", ".json", ".md", ".xml", ".txt", ".yml", ".yaml")
SKIP = (".git", ".github")

# Directories that must NEVER be published, whatever the reference scan says.
# Files stay in the repo (history, in case a relationship is revived) but are
# always kept out of the deployed site. Add a path prefix + a one-line reason.
ALWAYS_EXCLUDE = {
    "/schools/hualong/": "2026-07 不合作單位，全站不上線",
}

# Path prefixes whose images are served by the changhua-bilingual-photos-proxy
# Cloudflare Worker straight from R2 (see worker/), not by GitHub Pages — so
# every image under here is dropped from the Pages artifact regardless of
# whether it's referenced. Non-image files (html/css/js/pdf/audio) under the
# same prefix are unaffected; the Worker only intercepts image extensions.
R2_SERVED_PREFIXES = ("/schools/",)


def always_excluded(path):
    return any(path.startswith(prefix) for prefix in ALWAYS_EXCLUDE)


def r2_served_image(path):
    return path.lower().endswith(IMG_EXT) and any(path.startswith(p) for p in R2_SERVED_PREFIXES)

refs = set()
tref = re.compile(r'[^\s"\'()<>]+\.(?:jpg|jpeg|png|gif|webp|svg)', re.I)
for dp, dns, fns in os.walk("."):
    dns[:] = [d for d in dns if d not in SKIP]
    for fn in fns:
        if not fn.lower().endswith(TEXT_EXT):
            continue
        try:
            txt = open(os.path.join(dp, fn), encoding="utf-8").read()
        except Exception:
            continue
        for m in tref.findall(txt):
            refs.add(os.path.basename(unquote(m)).lower())

unref = []
forced = []
r2_served = []
total = 0
for dp, dns, fns in os.walk("."):
    dns[:] = [d for d in dns if d not in SKIP]
    for fn in fns:
        full = os.path.join(dp, fn)
        rel = full[1:]  # strip '.', keep leading '/'
        if always_excluded(rel):
            # every file type, not just images — the whole directory stays offline
            forced.append(rel)
            total += os.path.getsize(full)
            continue
        if not fn.lower().endswith(IMG_EXT):
            continue
        if r2_served_image(rel):
            r2_served.append(rel)
            total += os.path.getsize(full)
            continue
        if fn.lower() not in refs:
            unref.append(rel)
            total += os.path.getsize(full)

unref.sort()
forced.sort()
r2_served.sort()
with open(".pages-exclude", "w", encoding="utf-8") as f:
    f.write("# Auto-generated by tools/gen-pages-exclude.py\n")
    f.write("# Images not referenced by any page. Excluded from the PUBLISHED Pages\n")
    f.write("# artifact only; files remain in the repo. Re-run the script after\n")
    f.write("# adding photos or wiring up new pages.\n")
    if forced:
        f.write("#\n# Always excluded (ALWAYS_EXCLUDE in tools/gen-pages-exclude.py) —\n")
        for prefix, why in sorted(ALWAYS_EXCLUDE.items()):
            f.write(f"#   {prefix}  {why}\n")
        for p in forced:
            f.write(p + "\n")
    if r2_served:
        f.write("#\n# Served from R2 by the changhua-bilingual-photos-proxy Worker (see\n")
        f.write("# worker/), not by Pages — excluded from the artifact regardless of use —\n")
        for p in r2_served:
            f.write(p + "\n")
    f.write("#\n# Unreferenced images —\n")
    for p in unref:
        f.write(p + "\n")
print(f"wrote .pages-exclude: {len(unref)} unreferenced + {len(forced)} always-excluded + "
      f"{len(r2_served)} R2-served, {total/1048576:.0f} MB excluded from publish")
