#!/usr/bin/env python3
"""Stamp every hand-written page's /assets/* references with a content hash.

    python3 tools/stamp_assets.py --check   # report only, non-zero if stale
    python3 tools/stamp_assets.py           # rewrite in place

Idempotent: running it twice in a row changes nothing. Pages generated by
build.py are stamped by build.py itself (same shared function), so this is safe
to run over the whole tree either way.

Run it after changing anything under /assets/, then commit the touched HTML.
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from asset_version import stamp_html  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SKIP_DIRS = {".git", "node_modules", "_reference", "worker"}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="don't write; exit 1 if any page is out of date")
    ap.add_argument("--root", default=None,
                    help="site root to stamp (default: the repo). The deploy "
                         "workflow points this at the staged _site/ so that "
                         "production is stamped even if the repo copy lagged.")
    args = ap.parse_args()

    root = Path(args.root).resolve() if args.root else ROOT

    changed, scanned = [], 0
    for path in sorted(root.rglob("*.html")):
        if SKIP_DIRS & set(path.relative_to(root).parts):
            continue
        scanned += 1
        before = path.read_text(encoding="utf-8")
        after = stamp_html(before, root)
        if after != before:
            changed.append(path.relative_to(root))
            if not args.check:
                path.write_text(after, encoding="utf-8")

    print(f"scanned {scanned} html files")
    if not changed:
        print("all /assets/ references already carry the current hash ✅")
        return 0

    verb = "out of date" if args.check else "stamped"
    print(f"{len(changed)} {verb}:")
    for c in changed[:40]:
        print(f"  {c}")
    if len(changed) > 40:
        print(f"  … and {len(changed) - 40} more")
    if args.check:
        print("\nrun `python3 tools/stamp_assets.py` and commit the result")
        return 1
    print("\ncommit the touched HTML so the new URLs reach production")
    return 0


if __name__ == "__main__":
    sys.exit(main())
